server.port=8081
spring.application.name=wallet-service

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=
spring.jpa.properties.hibernate.dialect=
spring.jpa.properties.hibernate.format_sql=

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
